#!/bin/bash

#SBATCH -n48
#SBATCH --time=1:00:00
#SBATCH --account=FUA35_SOLBOUT5
#SBATCH --partition=skl_fua_prod
#SBATCH --output output.log
#SBATCH --error error.log

cd $SLURM_SUBMIT_DIR
mpirun -np $SLURM_NTASKS ../storm-public/storm2d/storm2d
